import Foundation
import SwiftData
import Testing

@testable import WorkoutTracker

// The only store that matters is the one already on the user's phone, holding
// training data that exists nowhere else. Presets added a model type, two
// relationships and four attributes; SwiftData should infer that migration, and
// "should" is not evidence (codex-review, finding 6).
//
// `Fixtures/LegacyStore.store` was generated by the app at commit `5239ef2` —
// the build actually installed on the phone — and is opened here with the
// current schema. Regenerate it from the *installed* commit whenever the shape
// changes again; a fixture written by today's code would prove nothing.

struct LegacyStoreMigrationTests {

    /// Copies the read-only fixture somewhere writable: SwiftData opens stores
    /// read-write and would migrate the bundle copy in place.
    private func openedFixture() throws -> (ModelContext, URL) {
        let bundle = Bundle(for: BundleMarker.self)
        let source = try #require(
            bundle.url(forResource: "LegacyStore", withExtension: "store"),
            "the legacy fixture must ship with the test bundle")
        let directory = FileManager.default.temporaryDirectory
            .appending(path: "legacy-\(UUID().uuidString)", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let copy = directory.appending(path: "LegacyStore.store")
        try FileManager.default.copyItem(at: source, to: copy)

        let container = try WorkoutTrackerStore.makeContainer(url: copy)
        return (ModelContext(container), directory)
    }

    private final class BundleMarker {}

    @Test func aPresetLessStoreOpensAndKeepsItsHistory() throws {
        let (context, directory) = try openedFixture()
        defer { try? FileManager.default.removeItem(at: directory) }

        let workouts = try context.fetch(FetchDescriptor<Workout>())
        #expect(workouts.count == 1, "the old workout must survive the migration")
        let entry = try #require(workouts.first?.entries?.first)
        #expect(entry.snapshotExerciseName == "Seated Row")
        #expect(entry.snapshotMachineLabel == "Cable Row 2")

        let sets = try context.fetch(FetchDescriptor<SetRecord>())
        #expect(sets.count == 1)
        let set = try #require(sets.first)
        #expect(set.reps == 8)
        #expect(set.weightValue == 70)
        #expect(set.normalizedKg == 70)
        #expect(set.completedAt != nil)
    }

    /// Milestone 9, ticket 04: the move-record fields arrive nil — nothing was
    /// moved on this store yet — and opening the fixture does not run the move
    /// (that needs the seeder crossing into catalog version 5).
    @Test func dumbbellMoveRecordArrivesNil() throws {
        let (context, directory) = try openedFixture()
        defer { try? FileManager.default.removeItem(at: directory) }
        let prefs = try #require(try context.fetch(FetchDescriptor<AppPreferences>()).first)
        #expect(prefs.dumbbellHistoryMovedSets == nil)
        #expect(prefs.dumbbellHistoryMovedAt == nil)
        #expect(prefs.dumbbellHistoryCheckedAt == nil)
        // D51 provenance fields on the fixture's one entry: never reclassified.
        let entry = try #require(try context.fetch(FetchDescriptor<ExerciseEntry>()).first)
        #expect(entry.reclassifiedAt == nil)
        #expect(entry.reclassifiedFromExerciseName == nil)
    }

    /// Milestone 9, ticket 02: the workout name arrives nil — "no name typed",
    /// which is the truth about every workout logged before names existed —
    /// and the title still derives exactly as it did.
    @Test func workoutNameArrivesNilAndTheTitleStillDerives() throws {
        let (context, directory) = try openedFixture()
        defer { try? FileManager.default.removeItem(at: directory) }
        let workout = try #require(try context.fetch(FetchDescriptor<Workout>()).first)
        #expect(workout.name == nil)
        #expect(workout.historyTitle == "Seated Row")
    }

    /// Every field presets added must materialise as "nobody recorded that",
    /// which is the truth about work logged before presets existed.
    @Test func presetFieldsArriveEmptyRatherThanBroken() throws {
        let (context, directory) = try openedFixture()
        defer { try? FileManager.default.removeItem(at: directory) }

        let entry = try #require(try context.fetch(FetchDescriptor<ExerciseEntry>()).first)
        #expect(entry.preset == nil)
        #expect(entry.snapshotPresetID == nil)
        #expect(entry.snapshotPresetName == nil)

        let machine = try #require(try context.fetch(FetchDescriptor<MachineInstance>()).first)
        #expect(machine.defaultPresetID == nil)

        let set = try #require(try context.fetch(FetchDescriptor<SetRecord>()).first)
        #expect(set.prefilledAt == nil)

        let exercise = try #require(try context.fetch(FetchDescriptor<Exercise>()).first)
        #expect((exercise.presets ?? []).isEmpty)
        #expect(try context.fetch(FetchDescriptor<ExercisePreset>()).isEmpty)
    }

    /// D39's field must materialise as "this weight was entered as a total",
    /// which is the truth about every set logged before 2026-08-22. A migration
    /// that produced 0 instead of nil would render every old set as loaded on a
    /// zero-weight bar.
    @Test func theBarWeightArrivesEmptyOnPreBarSets() throws {
        let (context, directory) = try openedFixture()
        defer { try? FileManager.default.removeItem(at: directory) }

        let set = try #require(try context.fetch(FetchDescriptor<SetRecord>()).first)
        #expect(set.barWeightValue == nil)
        #expect(set.barNormalizedKg == nil)
        // The weight it was logged with is untouched by the new column.
        #expect(set.weightValue == 70)
        #expect(WorkoutSession.platesPerSide(of: set) == nil)
    }

    /// Milestone 7 added heart-rate fields to `Workout` and rest-mode fields to
    /// `ExerciseRestOverride`, plus two preferences. Every one must materialise
    /// as "nobody recorded that" — which is the truth about every workout logged
    /// before 2026-08-22. A migration that produced 0 instead of nil would
    /// render old workouts as having a measured heart rate of zero.
    @Test func heartRateFieldsArriveEmptyOnPreHeartRateData() throws {
        let (context, directory) = try openedFixture()
        defer { try? FileManager.default.removeItem(at: directory) }

        let workout = try #require(try context.fetch(FetchDescriptor<Workout>()).first)
        #expect(workout.averageHeartRate == nil)
        #expect(workout.maxHeartRate == nil)
        #expect(workout.activeEnergyKilocalories == nil)
        #expect(workout.zoneSeconds.isEmpty)

        // And the summary built from it says nothing about the heart at all.
        let summary = WorkoutSummaryBuilder.summary(for: workout)
        #expect(!summary.hasHeartRate)
        #expect(!summary.exercises.isEmpty, "the workout itself still renders")

        let preferences = try #require(
            AppPreferences.canonical(of: try context.fetch(FetchDescriptor<AppPreferences>())))
        #expect(preferences.measuredMaxHeartRate == nil)
        #expect(preferences.birthDate == nil)
    }

    /// Old sets group together under "no preset" and keep their records — they
    /// do not vanish from a PR table because a new dimension appeared.
    @Test func oldSetsKeepTheirRecordsInTheNoPresetGroup() throws {
        let (context, directory) = try openedFixture()
        defer { try? FileManager.default.removeItem(at: directory) }

        let entry = try #require(try context.fetch(FetchDescriptor<ExerciseEntry>()).first)
        let inputs = try context.fetch(FetchDescriptor<SetRecord>())
            .filter { $0.completedAt != nil }
            .map { set in
                RecordSetInput(
                    loadType: entry.snapshotLoadType,
                    exerciseID: entry.snapshotExerciseID,
                    machineID: entry.snapshotMachineID,
                    modelID: entry.snapshotModelID,
                    presetID: entry.snapshotPresetID,
                    setType: set.type, reps: set.reps,
                    weightValue: set.weightValue, weightUnit: set.weightUnit,
                    normalizedKg: set.normalizedKg, completedAt: set.completedAt)
            }
        let machineID = try #require(entry.snapshotMachineID)
        let grouped = RecordsMath.grouped(inputs)
        #expect(grouped[.machine(machineID, preset: nil)]?.count == 1)
        #expect(
            RecordsMath.repCountBests(among: inputs, loadType: .weighted)[8]?.normalizedKg == 70,
            "a pre-preset best must still be a best")
    }

    /// And the export still works over it — the backup must not need presets to
    /// exist to describe a store that has none.
    @Test func aPresetLessStoreStillExports() throws {
        let (context, directory) = try openedFixture()
        defer { try? FileManager.default.removeItem(at: directory) }

        let snapshot = try ExportCollector(appVersion: "test").snapshot(from: context)
        #expect(snapshot.counts.workouts == 1)
        #expect(snapshot.counts.presets == 0)
        #expect(snapshot.presets.isEmpty)
        let entry = try #require(snapshot.workouts.first?.entries.first)
        #expect(entry.presetID == nil)
        #expect(entry.presetName == nil)

        let rows = TestCSV.rows(ExportCSV.render(snapshot))
        #expect(rows.count == 2, "header plus the one logged set")
        #expect(TestCSV.value("presetName", in: rows[1]) == "")
        #expect(try ExportJSON.decode(try ExportJSON.data(snapshot)) == snapshot)
    }
}
