#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — authored for this repo by the /wizard skill.
# ──────────────────────────────────────────────────────────────────────────

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_FILE="$PROJECT_DIR/WorkoutTracker.xcodeproj/project.pbxproj"
SCHEME="WorkoutTracker"
DERIVED="$PROJECT_DIR/build/DerivedData"

# detect_team_id — read the Team ID (the OU field) off the Apple Development
# certificate in the keychain. Empty if no certificate exists yet.
detect_team_id() {
  security find-certificate -c "Apple Development" -p 2>/dev/null \
    | openssl x509 -noout -subject 2>/dev/null \
    | tr ',/' '\n\n' \
    | grep -E '^[[:space:]]*OU[[:space:]]*=' \
    | head -1 | sed -E 's/.*=[[:space:]]*//' | tr -d '[:space:]'
}

# has_signing_identity — true once Xcode has issued a development certificate.
has_signing_identity() {
  security find-identity -v -p codesigning 2>/dev/null | grep -q "Apple Development"
}

# write_team_id TEAMID — upsert DEVELOPMENT_TEAM beside every automatic
# signing block in the Xcode project. Idempotent; leaves the test target
# (which has signing disabled) untouched.
write_team_id() {
  local team="$1" tmp
  tmp=$(mktemp)
  awk -v team="$team" '
    /^[[:space:]]*DEVELOPMENT_TEAM = /{ next }
    { print }
    /^[[:space:]]*CODE_SIGN_STYLE = Automatic;/{
      match($0, /^[[:space:]]*/)
      print substr($0, 1, RLENGTH) "DEVELOPMENT_TEAM = " team ";"
    }
  ' "$PROJECT_FILE" > "$tmp" && mv "$tmp" "$PROJECT_FILE"
  printf '  %s✓ wrote%s DEVELOPMENT_TEAM = %s into the Xcode project\n' "$GREEN" "$RESET" "$team"
}

# first_connected_device — "UDID<TAB>Name" of a connected iPhone, if any.
first_connected_device() {
  local json; json=$(mktemp)
  xcrun devicectl list devices --json-output "$json" >/dev/null 2>&1 || { rm -f "$json"; return 1; }
  python3 - "$json" << 'PY'
import json, sys
try:
    devices = json.load(open(sys.argv[1]))["result"]["devices"]
except Exception:
    sys.exit(1)
for d in devices:
    props = d.get("deviceProperties", {})
    conn  = d.get("connectionProperties", {})
    if conn.get("tunnelState") in ("disconnected", None) and conn.get("pairingState") != "paired":
        continue
    udid = d.get("hardwareProperties", {}).get("udid") or d.get("identifier", "")
    name = props.get("name", "iPhone")
    if udid:
        print(f"{udid}\t{name}")
        break
PY
  rm -f "$json"
}

TOTAL_STAGES=5

banner "Install WorkoutTracker on your iPhone"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Apple ID — give Xcode a signing identity"
if has_signing_identity; then
  say "You already have an Apple Development certificate. Skipping ahead."
  pause "Press Enter to continue"
else
  say "iOS refuses to run an app that nobody signed. Xcode issues that signature"
  say "once an Apple ID is attached — a free account is enough."
  printf '\n'
  step "Xcode is opening. Go to: Xcode ▸ Settings ▸ Accounts"
  step "Click + (bottom left) ▸ Apple ID ▸ sign in (password + 2FA)."
  step "Your name appears with a team such as 'Eric Lee (Personal Team)'."
  open_url "xcode://"
  printf '\n'
  note "A free account works but its builds expire after 7 days — re-run this"
  note "script to reinstall. A paid Developer Program account lasts a year."
  printf '\n'
  until has_signing_identity; do
    pause "Signed in? Press Enter and I'll check for the certificate"
    has_signing_identity || warn "No Apple Development certificate yet — finish the sign-in, then retry."
  done
  printf '  %s✓%s Apple Development certificate found.\n' "$GREEN" "$RESET"
  pause "Press Enter to continue"
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Team ID — tell the project who signs it"
TEAM_ID=$(detect_team_id || true)
if [[ -n "$TEAM_ID" ]]; then
  say "Detected Team ID from your certificate: ${BOLD}${TEAM_ID}${RESET}"
  if ! confirm "Use this Team ID?"; then TEAM_ID=""; fi
fi
if [[ -z "$TEAM_ID" ]]; then
  step "In Xcode ▸ Settings ▸ Accounts, select your Apple ID."
  step "The team list shows a 10-character ID in the Team ID column."
  ask TEAM_ID "Paste your Team ID:"
fi
if [[ -z "$TEAM_ID" ]]; then
  warn "No Team ID — cannot sign. Re-run once you have one."
  exit 1
fi
write_team_id "$TEAM_ID"
note "Bundle ID is com.ericlee4992.workouttracker — must be globally unique."
note "If Xcode later says it is taken, change it in the project and re-run."
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "iPhone — connect it and unlock developer installs"
DEVICE_LINE=$(first_connected_device || true)
if [[ -z "$DEVICE_LINE" ]]; then
  say "Your Mac has to see the phone before it can install anything."
  printf '\n'
  step "Plug the iPhone into this Mac with a cable."
  step "Unlock the phone. If it asks 'Trust This Computer?' tap Trust, enter your passcode."
  step "On the phone: Settings ▸ Privacy & Security ▸ Developer Mode ▸ turn ON."
  step "The phone restarts. After it reboots, unlock it and confirm Developer Mode."
  printf '\n'
  note "Developer Mode only appears in Settings after a Mac has tried to talk to"
  note "the phone — if you don't see it, plug in and unlock first, then look again."
  printf '\n'
  until [[ -n "$DEVICE_LINE" ]]; do
    pause "Phone connected and Developer Mode on? Press Enter to check"
    DEVICE_LINE=$(first_connected_device || true)
    [[ -n "$DEVICE_LINE" ]] || warn "No device visible yet — keep it plugged in and unlocked."
  done
fi
DEVICE_UDID="${DEVICE_LINE%%$'\t'*}"
DEVICE_NAME="${DEVICE_LINE#*$'\t'}"
printf '  %s✓%s Found %s\n' "$GREEN" "$RESET" "$DEVICE_NAME"
note "UDID $DEVICE_UDID"
pause "Press Enter to build"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Build & install"
say "Building for ${DEVICE_NAME} and installing. First run is slow — Xcode has"
say "to create a provisioning profile for this app and device."
printf '\n'
BUILD_LOG=$(mktemp)
if xcodebuild -project "$PROJECT_DIR/WorkoutTracker.xcodeproj" \
      -scheme "$SCHEME" -configuration Debug \
      -destination "platform=iOS,id=$DEVICE_UDID" \
      -derivedDataPath "$DERIVED" \
      -allowProvisioningUpdates build > "$BUILD_LOG" 2>&1; then
  printf '  %s✓%s Build succeeded.\n' "$GREEN" "$RESET"
else
  warn "Build failed. Last lines:"
  grep -E "error:|Signing|Provisioning|No profiles" "$BUILD_LOG" | tail -12 || tail -12 "$BUILD_LOG"
  printf '\n'
  note "Full log: $BUILD_LOG"
  note "Most common cause: the bundle ID is already taken by another Apple account."
  exit 1
fi
APP_PATH="$DERIVED/Build/Products/Debug-iphoneos/WorkoutTracker.app"
if [[ ! -d "$APP_PATH" ]]; then
  warn "Built, but no .app at $APP_PATH"; exit 1
fi
if xcrun devicectl device install app --device "$DEVICE_UDID" "$APP_PATH" >/dev/null 2>&1; then
  printf '  %s✓%s Installed on %s\n' "$GREEN" "$RESET" "$DEVICE_NAME"
else
  warn "Install failed — usually means the phone locked mid-install."
  note "Unlock it and re-run this script; the build is cached so it'll be quick."
  exit 1
fi
rm -f "$BUILD_LOG"
pause "Press Enter for the last step"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Trust the app on your phone"
say "The app is installed but iOS won't launch it until you vouch for the"
say "certificate that signed it. This is a one-time step per Apple ID."
printf '\n'
step "On the phone: Settings ▸ General ▸ VPN & Device Management"
step "Under 'Developer App', tap your Apple ID."
step "Tap 'Trust \"...\"' and confirm."
printf '\n'
say "Then find WorkoutTracker on your home screen and open it."
printf '\n'
note "First run seeds the equipment catalog, so the Exercises tab fills in but"
note "Gyms is empty — create your gym and its machines before your first workout."
printf '\n'
pause "Press Enter when the app opens"

finish
note "Dogfooding checklist — the things only a real session can prove:"
note "  - logging a set feels fast enough mid-workout"
note "  - force-quit mid-workout, reopen: the workout resumes intact"
note "  - rest-timer notification fires with the phone locked in your pocket"
note "  - prefill shows the right numbers on your second session"
printf '\n'
